### ISSUE TITLE
Issue with pyrodigal still exists

### ISSUE THREAD

**Issue by joelwwh** [Chrisjrt/hafeZ#10]
I just tried to run the test files provided and still came to this error:

AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'

**Comment by Chrisjrt** [comment]
My bad, looks like when I fixed the bug I forgot to update the environment file in the repo. The bioconda install has the correct version of pyrodigal on it. So just install from bioconda this should sort you out. 

`mamba create -n hafeZ -c conda-forge -c bioconda -c defaults hafez`

Let me know if this doesn't fix it :)

**Comment by joelwwh** [comment]
Fixed - thank you!

**Comment by Chrisjrt** [comment]
Awesome :) Closing then, plus update README so users are now pointed to the bioconda install.
